language: go
go: 
  - "1.11"

before_install:
  - go get github.com/milagro-crypto/amcl || true
  - (cd $GOPATH/src/github.com/milagro-crypto/amcl/version3/go/; (echo "21"; echo "0") | python config64.py)

before_script:
  - go get github.com/stretchr/testify

script: 
  - go test -v ./...
  - go test ./... -run nothing -bench=. -cpu=1,2,4 -benchtime=2s

git:
  depth: 1

notifications:
  email: false