language: go
go: 
  - "1.11"

before_install:
  - go get github.com/milagro-crypto/amcl || true
  - (echo "21"; echo "0") | python $GOPATH/src/github.com/milagro-crypto/amcl/version3/go/config64.py

git:
  depth: 1

notifications:
  email: false