language: go
go: 
  - "1.11"

env:
  - DEP_VERSION="0.5.0"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

script: 
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic
  # - go test ./... -timeout=60m -run nothing -bench=. -cpu=1,2,4 -benchtime=2s

after_success:
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 1

notifications:
  email: false