version: 1
accounts:
  - name: alexis
    coins: ["1000000nym"]        
  - name: ania
    coins: ["1000000nym"]
  - name: claudia
    coins: ["1000000nym"]
  - name: dave
    coins: ["1000000nym", "100000000stake"]
  - name: harry
    coins: ["1000000nym"]
  - name: jedrzej
    coins: ["1000000nym"]
  - name: jess
    coins: ["1000000nym"]
  - name: mathieu
    coins: ["1000000nym"]         
  - name: roebuck
    coins: ["1000000nym"]
  - name: theo
    coins: ["1000000nym"]
validator:
  name: dave
  staked: "100000000stake"
