# Coconut IA server configuration file.

[Server]

  # Identifier is the human readable identifier for the node (eg: FQDN).
  Identifier = "Test IA Server2"

  # Addresses are the IP address/port combinations that the server will bind
  # to for incoming connections.
  Addresses = [ "127.0.0.1:4001" ]

  # MaximumAttributes specifies the maximum number of attributes the server will sign.
  MaximumAttributes = 5

  # VerificationKeyFile specifies the file containing the Coconut Verification Key.
  VerificationKeyFile = "verification2.pem"

  # SecretKeyFile specifies the file containing the Coconut Secret Key.
  SecretKeyFile = "secret2.pem"
    
[Logging]

  # Disable disables logging entirely.
  Disable = false

  # File specifies the log file, if omitted stdout will be used.
  # File = "/var/log/coconutIA.log"

  # Level specifies the log level out of `CRITICAL`, `ERROR`, `WARNING`,
  # `NOTICE`, `INFO` and `DEBUG`.
  #
  # Warning: The `DEBUG` log level is unsafe for production use.
  Level = "DEBUG"


[Debug]

  # RegenerateKeys = true