// Copyright 2020 Nym Technologies SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/nymtech/nym/validator/nym/directory/models"
	mock "github.com/stretchr/testify/mock"
)

// BatchSanitizer is an autogenerated mock type for the BatchSanitizer type
type BatchSanitizer struct {
	mock.Mock
}

// Sanitize provides a mock function with given fields: input
func (_m *BatchSanitizer) Sanitize(input models.BatchMixStatus) models.BatchMixStatus {
	ret := _m.Called(input)

	var r0 models.BatchMixStatus
	if rf, ok := ret.Get(0).(func(models.BatchMixStatus) models.BatchMixStatus); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(models.BatchMixStatus)
	}

	return r0
}
