# ERC20 Nym Faucet configuration file.

[Server]

  # Identifier is the human readable identifier for the node (eg: FQDN).
  Identifier = "Faucet"

  # Addresses are the IP address/port combinations that the server will bind
  # to for incoming connections.
  Addresses = [ "0.0.0.0:9000" ]

  # GRPCAddresses are the IP address:port combinations that the server will bind
  # to for incoming grpcs.
  GRPCAddresses = [ ]

  # DataDir specifies path to a .db file holding relevant server-specific persistent data.
  # Currently nothing is being stored, but this is included for completion sake.
  DataDir = "~/nymnet/faucet/"
  
  # MaximumAttributes specifies the maximum number of attributes the system supports.
  MaximumAttributes = 5

  # BlockchainNodeAddresses specifies addresses of a blockchain nodes
  # to which the issuer should send all relevant requests. 
  # Note that only a single request will ever be sent, but multiple addresses are provided in case 
  # the particular node was unavailable.
  BlockchainNodeAddresses = [  ]

[Faucet]
  # EthereumNodeAddress defines address of an Ethereum node to which transactions are sent.
  EthereumNodeAddress = "https://ropsten.infura.io/v3/131453a5470641cd9f64942eecd8add2"
 
  # NymContract defined address of the ERC20 token Nym contract. It is expected to be provided in hex format.
  NymContract = "0xE80025228D5448A55B995c829B89567ECE5203d3"

  # PipeAccount defines address of Ethereum account that pipes Nym ERC20 into Nym Tendermint coins.
  # It is expected to be provided in hex format.
  PipeAccount = "0xb749305b3293477b4d6b498b22db5353c9acb3f1"

  # BlockchainKeyFile specifies the file containing the Blockchain relevant keys.
  BlockchainKeyFile = "~/nymnet/faucet/faucet.key"

[Logging]

  # Disable disables logging entirely.
  Disable = false

  # File specifies the log file, if omitted stdout will be used.
  # File = "/var/log/faucet.log"

  # Level specifies the log level out of `CRITICAL`, `ERROR`, `WARNING`,
  # `NOTICE`, `INFO` and `DEBUG`.
  #
  # Warning: The `DEBUG` log level is unsafe for production use.
  Level = "DEBUG"


[Debug]

  # In future that would require some refactoring and renaming, because it's not doing exactly what the name suggests,
  # The server will not communicate with Tendermint blockchain and won't create the relevant client because in this case 
  # it does not need to. However, it will still call the Ethereum contract.
  DisableAllBlockchainCommunication = true
