// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client/rpc/clienttypes/types.proto

package clienttypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	scheme "github.com/nymtech/nym-validator/crypto/coconut/scheme"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: this is really a placeholder which will change once the system is properly rewritten
type ServiceProvider struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=Ip,json=ip,proto3" json:"Ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceProvider) Reset()         { *m = ServiceProvider{} }
func (m *ServiceProvider) String() string { return proto.CompactTextString(m) }
func (*ServiceProvider) ProtoMessage()    {}
func (*ServiceProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{0}
}

func (m *ServiceProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceProvider.Unmarshal(m, b)
}
func (m *ServiceProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceProvider.Marshal(b, m, deterministic)
}
func (m *ServiceProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceProvider.Merge(m, src)
}
func (m *ServiceProvider) XXX_Size() int {
	return xxx_messageInfo_ServiceProvider.Size(m)
}
func (m *ServiceProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceProvider.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceProvider proto.InternalMessageInfo

func (m *ServiceProvider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceProvider) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ServiceProvider) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type CredentialMaterials struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Secret               []byte   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Sequence             []byte   `protobuf:"bytes,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialMaterials) Reset()         { *m = CredentialMaterials{} }
func (m *CredentialMaterials) String() string { return proto.CompactTextString(m) }
func (*CredentialMaterials) ProtoMessage()    {}
func (*CredentialMaterials) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{1}
}

func (m *CredentialMaterials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialMaterials.Unmarshal(m, b)
}
func (m *CredentialMaterials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialMaterials.Marshal(b, m, deterministic)
}
func (m *CredentialMaterials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialMaterials.Merge(m, src)
}
func (m *CredentialMaterials) XXX_Size() int {
	return xxx_messageInfo_CredentialMaterials.Size(m)
}
func (m *CredentialMaterials) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialMaterials.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialMaterials proto.InternalMessageInfo

func (m *CredentialMaterials) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *CredentialMaterials) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *CredentialMaterials) GetSequence() []byte {
	if m != nil {
		return m.Sequence
	}
	return nil
}

type Request struct {
	// Types that are valid to be assigned to Value:
	//	*Request_GetCredential
	//	*Request_SpendCredential
	//	*Request_GetProviders
	//	*Request_Rerandomize
	//	*Request_Flush
	Value                isRequest_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type isRequest_Value interface {
	isRequest_Value()
}

type Request_GetCredential struct {
	GetCredential *RequestGetCredential `protobuf:"bytes,2,opt,name=getCredential,proto3,oneof"`
}

type Request_SpendCredential struct {
	SpendCredential *RequestSpendCredential `protobuf:"bytes,3,opt,name=spendCredential,proto3,oneof"`
}

type Request_GetProviders struct {
	GetProviders *RequestGetServiceProviders `protobuf:"bytes,4,opt,name=getProviders,proto3,oneof"`
}

type Request_Rerandomize struct {
	Rerandomize *RequestRerandomize `protobuf:"bytes,5,opt,name=rerandomize,proto3,oneof"`
}

type Request_Flush struct {
	Flush *RequestFlush `protobuf:"bytes,6,opt,name=flush,proto3,oneof"`
}

func (*Request_GetCredential) isRequest_Value() {}

func (*Request_SpendCredential) isRequest_Value() {}

func (*Request_GetProviders) isRequest_Value() {}

func (*Request_Rerandomize) isRequest_Value() {}

func (*Request_Flush) isRequest_Value() {}

func (m *Request) GetValue() isRequest_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Request) GetGetCredential() *RequestGetCredential {
	if x, ok := m.GetValue().(*Request_GetCredential); ok {
		return x.GetCredential
	}
	return nil
}

func (m *Request) GetSpendCredential() *RequestSpendCredential {
	if x, ok := m.GetValue().(*Request_SpendCredential); ok {
		return x.SpendCredential
	}
	return nil
}

func (m *Request) GetGetProviders() *RequestGetServiceProviders {
	if x, ok := m.GetValue().(*Request_GetProviders); ok {
		return x.GetProviders
	}
	return nil
}

func (m *Request) GetRerandomize() *RequestRerandomize {
	if x, ok := m.GetValue().(*Request_Rerandomize); ok {
		return x.Rerandomize
	}
	return nil
}

func (m *Request) GetFlush() *RequestFlush {
	if x, ok := m.GetValue().(*Request_Flush); ok {
		return x.Flush
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_GetCredential)(nil),
		(*Request_SpendCredential)(nil),
		(*Request_GetProviders)(nil),
		(*Request_Rerandomize)(nil),
		(*Request_Flush)(nil),
	}
}

type RequestGetCredential struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestGetCredential) Reset()         { *m = RequestGetCredential{} }
func (m *RequestGetCredential) String() string { return proto.CompactTextString(m) }
func (*RequestGetCredential) ProtoMessage()    {}
func (*RequestGetCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{3}
}

func (m *RequestGetCredential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestGetCredential.Unmarshal(m, b)
}
func (m *RequestGetCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestGetCredential.Marshal(b, m, deterministic)
}
func (m *RequestGetCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestGetCredential.Merge(m, src)
}
func (m *RequestGetCredential) XXX_Size() int {
	return xxx_messageInfo_RequestGetCredential.Size(m)
}
func (m *RequestGetCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestGetCredential.DiscardUnknown(m)
}

var xxx_messageInfo_RequestGetCredential proto.InternalMessageInfo

func (m *RequestGetCredential) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type RequestSpendCredential struct {
	Credential           *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Materials            *CredentialMaterials   `protobuf:"bytes,2,opt,name=materials,proto3" json:"materials,omitempty"`
	Provider             *ServiceProvider       `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RequestSpendCredential) Reset()         { *m = RequestSpendCredential{} }
func (m *RequestSpendCredential) String() string { return proto.CompactTextString(m) }
func (*RequestSpendCredential) ProtoMessage()    {}
func (*RequestSpendCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{4}
}

func (m *RequestSpendCredential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSpendCredential.Unmarshal(m, b)
}
func (m *RequestSpendCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSpendCredential.Marshal(b, m, deterministic)
}
func (m *RequestSpendCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSpendCredential.Merge(m, src)
}
func (m *RequestSpendCredential) XXX_Size() int {
	return xxx_messageInfo_RequestSpendCredential.Size(m)
}
func (m *RequestSpendCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSpendCredential.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSpendCredential proto.InternalMessageInfo

func (m *RequestSpendCredential) GetCredential() *scheme.ProtoSignature {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (m *RequestSpendCredential) GetMaterials() *CredentialMaterials {
	if m != nil {
		return m.Materials
	}
	return nil
}

func (m *RequestSpendCredential) GetProvider() *ServiceProvider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type RequestGetServiceProviders struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestGetServiceProviders) Reset()         { *m = RequestGetServiceProviders{} }
func (m *RequestGetServiceProviders) String() string { return proto.CompactTextString(m) }
func (*RequestGetServiceProviders) ProtoMessage()    {}
func (*RequestGetServiceProviders) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{5}
}

func (m *RequestGetServiceProviders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestGetServiceProviders.Unmarshal(m, b)
}
func (m *RequestGetServiceProviders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestGetServiceProviders.Marshal(b, m, deterministic)
}
func (m *RequestGetServiceProviders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestGetServiceProviders.Merge(m, src)
}
func (m *RequestGetServiceProviders) XXX_Size() int {
	return xxx_messageInfo_RequestGetServiceProviders.Size(m)
}
func (m *RequestGetServiceProviders) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestGetServiceProviders.DiscardUnknown(m)
}

var xxx_messageInfo_RequestGetServiceProviders proto.InternalMessageInfo

type RequestRerandomize struct {
	Credential           *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RequestRerandomize) Reset()         { *m = RequestRerandomize{} }
func (m *RequestRerandomize) String() string { return proto.CompactTextString(m) }
func (*RequestRerandomize) ProtoMessage()    {}
func (*RequestRerandomize) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{6}
}

func (m *RequestRerandomize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestRerandomize.Unmarshal(m, b)
}
func (m *RequestRerandomize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestRerandomize.Marshal(b, m, deterministic)
}
func (m *RequestRerandomize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestRerandomize.Merge(m, src)
}
func (m *RequestRerandomize) XXX_Size() int {
	return xxx_messageInfo_RequestRerandomize.Size(m)
}
func (m *RequestRerandomize) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestRerandomize.DiscardUnknown(m)
}

var xxx_messageInfo_RequestRerandomize proto.InternalMessageInfo

func (m *RequestRerandomize) GetCredential() *scheme.ProtoSignature {
	if m != nil {
		return m.Credential
	}
	return nil
}

type RequestFlush struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFlush) Reset()         { *m = RequestFlush{} }
func (m *RequestFlush) String() string { return proto.CompactTextString(m) }
func (*RequestFlush) ProtoMessage()    {}
func (*RequestFlush) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{7}
}

func (m *RequestFlush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFlush.Unmarshal(m, b)
}
func (m *RequestFlush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFlush.Marshal(b, m, deterministic)
}
func (m *RequestFlush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFlush.Merge(m, src)
}
func (m *RequestFlush) XXX_Size() int {
	return xxx_messageInfo_RequestFlush.Size(m)
}
func (m *RequestFlush) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFlush.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFlush proto.InternalMessageInfo

type Response struct {
	// Types that are valid to be assigned to Value:
	//	*Response_Exception
	//	*Response_GetCredential
	//	*Response_SpendCredential
	//	*Response_GetProviders
	//	*Response_Rerandomize
	//	*Response_Flush
	Value                isResponse_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{8}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type isResponse_Value interface {
	isResponse_Value()
}

type Response_Exception struct {
	Exception *ResponseException `protobuf:"bytes,1,opt,name=exception,proto3,oneof"`
}

type Response_GetCredential struct {
	GetCredential *ResponseGetCredential `protobuf:"bytes,2,opt,name=getCredential,proto3,oneof"`
}

type Response_SpendCredential struct {
	SpendCredential *ResponseSpendCredential `protobuf:"bytes,3,opt,name=spendCredential,proto3,oneof"`
}

type Response_GetProviders struct {
	GetProviders *ResponseGetServiceProviders `protobuf:"bytes,4,opt,name=getProviders,proto3,oneof"`
}

type Response_Rerandomize struct {
	Rerandomize *ResponseRerandomize `protobuf:"bytes,5,opt,name=rerandomize,proto3,oneof"`
}

type Response_Flush struct {
	Flush *ResponseFlush `protobuf:"bytes,6,opt,name=flush,proto3,oneof"`
}

func (*Response_Exception) isResponse_Value() {}

func (*Response_GetCredential) isResponse_Value() {}

func (*Response_SpendCredential) isResponse_Value() {}

func (*Response_GetProviders) isResponse_Value() {}

func (*Response_Rerandomize) isResponse_Value() {}

func (*Response_Flush) isResponse_Value() {}

func (m *Response) GetValue() isResponse_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Response) GetException() *ResponseException {
	if x, ok := m.GetValue().(*Response_Exception); ok {
		return x.Exception
	}
	return nil
}

func (m *Response) GetGetCredential() *ResponseGetCredential {
	if x, ok := m.GetValue().(*Response_GetCredential); ok {
		return x.GetCredential
	}
	return nil
}

func (m *Response) GetSpendCredential() *ResponseSpendCredential {
	if x, ok := m.GetValue().(*Response_SpendCredential); ok {
		return x.SpendCredential
	}
	return nil
}

func (m *Response) GetGetProviders() *ResponseGetServiceProviders {
	if x, ok := m.GetValue().(*Response_GetProviders); ok {
		return x.GetProviders
	}
	return nil
}

func (m *Response) GetRerandomize() *ResponseRerandomize {
	if x, ok := m.GetValue().(*Response_Rerandomize); ok {
		return x.Rerandomize
	}
	return nil
}

func (m *Response) GetFlush() *ResponseFlush {
	if x, ok := m.GetValue().(*Response_Flush); ok {
		return x.Flush
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_Exception)(nil),
		(*Response_GetCredential)(nil),
		(*Response_SpendCredential)(nil),
		(*Response_GetProviders)(nil),
		(*Response_Rerandomize)(nil),
		(*Response_Flush)(nil),
	}
}

type ResponseException struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseException) Reset()         { *m = ResponseException{} }
func (m *ResponseException) String() string { return proto.CompactTextString(m) }
func (*ResponseException) ProtoMessage()    {}
func (*ResponseException) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{9}
}

func (m *ResponseException) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseException.Unmarshal(m, b)
}
func (m *ResponseException) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseException.Marshal(b, m, deterministic)
}
func (m *ResponseException) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseException.Merge(m, src)
}
func (m *ResponseException) XXX_Size() int {
	return xxx_messageInfo_ResponseException.Size(m)
}
func (m *ResponseException) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseException.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseException proto.InternalMessageInfo

func (m *ResponseException) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResponseGetCredential struct {
	Credential           *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Materials            *CredentialMaterials   `protobuf:"bytes,2,opt,name=materials,proto3" json:"materials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ResponseGetCredential) Reset()         { *m = ResponseGetCredential{} }
func (m *ResponseGetCredential) String() string { return proto.CompactTextString(m) }
func (*ResponseGetCredential) ProtoMessage()    {}
func (*ResponseGetCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{10}
}

func (m *ResponseGetCredential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseGetCredential.Unmarshal(m, b)
}
func (m *ResponseGetCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseGetCredential.Marshal(b, m, deterministic)
}
func (m *ResponseGetCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseGetCredential.Merge(m, src)
}
func (m *ResponseGetCredential) XXX_Size() int {
	return xxx_messageInfo_ResponseGetCredential.Size(m)
}
func (m *ResponseGetCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseGetCredential.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseGetCredential proto.InternalMessageInfo

func (m *ResponseGetCredential) GetCredential() *scheme.ProtoSignature {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (m *ResponseGetCredential) GetMaterials() *CredentialMaterials {
	if m != nil {
		return m.Materials
	}
	return nil
}

type ResponseSpendCredential struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSpendCredential) Reset()         { *m = ResponseSpendCredential{} }
func (m *ResponseSpendCredential) String() string { return proto.CompactTextString(m) }
func (*ResponseSpendCredential) ProtoMessage()    {}
func (*ResponseSpendCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{11}
}

func (m *ResponseSpendCredential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSpendCredential.Unmarshal(m, b)
}
func (m *ResponseSpendCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSpendCredential.Marshal(b, m, deterministic)
}
func (m *ResponseSpendCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSpendCredential.Merge(m, src)
}
func (m *ResponseSpendCredential) XXX_Size() int {
	return xxx_messageInfo_ResponseSpendCredential.Size(m)
}
func (m *ResponseSpendCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSpendCredential.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSpendCredential proto.InternalMessageInfo

type ResponseGetServiceProviders struct {
	Providers            []*ServiceProvider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ResponseGetServiceProviders) Reset()         { *m = ResponseGetServiceProviders{} }
func (m *ResponseGetServiceProviders) String() string { return proto.CompactTextString(m) }
func (*ResponseGetServiceProviders) ProtoMessage()    {}
func (*ResponseGetServiceProviders) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{12}
}

func (m *ResponseGetServiceProviders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseGetServiceProviders.Unmarshal(m, b)
}
func (m *ResponseGetServiceProviders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseGetServiceProviders.Marshal(b, m, deterministic)
}
func (m *ResponseGetServiceProviders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseGetServiceProviders.Merge(m, src)
}
func (m *ResponseGetServiceProviders) XXX_Size() int {
	return xxx_messageInfo_ResponseGetServiceProviders.Size(m)
}
func (m *ResponseGetServiceProviders) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseGetServiceProviders.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseGetServiceProviders proto.InternalMessageInfo

func (m *ResponseGetServiceProviders) GetProviders() []*ServiceProvider {
	if m != nil {
		return m.Providers
	}
	return nil
}

type ResponseRerandomize struct {
	Credential           *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ResponseRerandomize) Reset()         { *m = ResponseRerandomize{} }
func (m *ResponseRerandomize) String() string { return proto.CompactTextString(m) }
func (*ResponseRerandomize) ProtoMessage()    {}
func (*ResponseRerandomize) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{13}
}

func (m *ResponseRerandomize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseRerandomize.Unmarshal(m, b)
}
func (m *ResponseRerandomize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseRerandomize.Marshal(b, m, deterministic)
}
func (m *ResponseRerandomize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseRerandomize.Merge(m, src)
}
func (m *ResponseRerandomize) XXX_Size() int {
	return xxx_messageInfo_ResponseRerandomize.Size(m)
}
func (m *ResponseRerandomize) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseRerandomize.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseRerandomize proto.InternalMessageInfo

func (m *ResponseRerandomize) GetCredential() *scheme.ProtoSignature {
	if m != nil {
		return m.Credential
	}
	return nil
}

type ResponseFlush struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseFlush) Reset()         { *m = ResponseFlush{} }
func (m *ResponseFlush) String() string { return proto.CompactTextString(m) }
func (*ResponseFlush) ProtoMessage()    {}
func (*ResponseFlush) Descriptor() ([]byte, []int) {
	return fileDescriptor_252a27e804793a46, []int{14}
}

func (m *ResponseFlush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseFlush.Unmarshal(m, b)
}
func (m *ResponseFlush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseFlush.Marshal(b, m, deterministic)
}
func (m *ResponseFlush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseFlush.Merge(m, src)
}
func (m *ResponseFlush) XXX_Size() int {
	return xxx_messageInfo_ResponseFlush.Size(m)
}
func (m *ResponseFlush) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseFlush.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseFlush proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ServiceProvider)(nil), "clienttypes.ServiceProvider")
	proto.RegisterType((*CredentialMaterials)(nil), "clienttypes.CredentialMaterials")
	proto.RegisterType((*Request)(nil), "clienttypes.Request")
	proto.RegisterType((*RequestGetCredential)(nil), "clienttypes.RequestGetCredential")
	proto.RegisterType((*RequestSpendCredential)(nil), "clienttypes.RequestSpendCredential")
	proto.RegisterType((*RequestGetServiceProviders)(nil), "clienttypes.RequestGetServiceProviders")
	proto.RegisterType((*RequestRerandomize)(nil), "clienttypes.RequestRerandomize")
	proto.RegisterType((*RequestFlush)(nil), "clienttypes.RequestFlush")
	proto.RegisterType((*Response)(nil), "clienttypes.Response")
	proto.RegisterType((*ResponseException)(nil), "clienttypes.ResponseException")
	proto.RegisterType((*ResponseGetCredential)(nil), "clienttypes.ResponseGetCredential")
	proto.RegisterType((*ResponseSpendCredential)(nil), "clienttypes.ResponseSpendCredential")
	proto.RegisterType((*ResponseGetServiceProviders)(nil), "clienttypes.ResponseGetServiceProviders")
	proto.RegisterType((*ResponseRerandomize)(nil), "clienttypes.ResponseRerandomize")
	proto.RegisterType((*ResponseFlush)(nil), "clienttypes.ResponseFlush")
}

func init() { proto.RegisterFile("client/rpc/clienttypes/types.proto", fileDescriptor_252a27e804793a46) }

var fileDescriptor_252a27e804793a46 = []byte{
	// 598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x18, 0xb4, 0x93, 0xfe, 0x24, 0x5f, 0xd2, 0x46, 0x6c, 0x4b, 0xeb, 0x86, 0x0a, 0xc2, 0x82, 0xd4,
	0x22, 0xa1, 0x58, 0x94, 0x03, 0x88, 0x03, 0x07, 0xca, 0x8f, 0x8b, 0x94, 0x36, 0xda, 0x9c, 0x38,
	0x21, 0x63, 0x7f, 0xa4, 0x96, 0x12, 0xdb, 0xec, 0x6e, 0x22, 0xca, 0x53, 0xf0, 0x3e, 0x3c, 0x02,
	0xcf, 0xc3, 0x1d, 0x65, 0xed, 0xc4, 0x76, 0xba, 0x6e, 0x50, 0x2f, 0x5c, 0x22, 0x7f, 0xce, 0xcc,
	0x64, 0x3d, 0xf3, 0x4d, 0x0c, 0xd4, 0x1b, 0x05, 0x18, 0x4a, 0x9b, 0xc7, 0x9e, 0x9d, 0x5c, 0xca,
	0xab, 0x18, 0x85, 0xad, 0x3e, 0xbb, 0x31, 0x8f, 0x64, 0x44, 0x1a, 0xb9, 0x2f, 0xda, 0x47, 0x1e,
	0xbf, 0x8a, 0x65, 0x64, 0x7b, 0x91, 0x17, 0x85, 0x13, 0x69, 0x0b, 0xef, 0x12, 0xc7, 0x68, 0x2b,
	0x64, 0x9e, 0x45, 0x2f, 0xa0, 0x35, 0x40, 0x3e, 0x0d, 0x3c, 0xec, 0xf3, 0x68, 0x1a, 0xf8, 0xc8,
	0x09, 0x81, 0xb5, 0xd0, 0x1d, 0xa3, 0x65, 0x76, 0xcc, 0xe3, 0x3a, 0x53, 0xd7, 0xc4, 0x82, 0x4d,
	0xd7, 0xf7, 0x39, 0x0a, 0x61, 0x55, 0xd4, 0xed, 0xf9, 0x48, 0xb6, 0xa1, 0x72, 0x16, 0x5b, 0x55,
	0x75, 0xb3, 0x12, 0xc4, 0xf4, 0x33, 0xec, 0x9c, 0x72, 0xf4, 0x31, 0x94, 0x81, 0x3b, 0xea, 0xb9,
	0x12, 0x79, 0xe0, 0x8e, 0x04, 0xd9, 0x85, 0xf5, 0xa9, 0x3b, 0x9a, 0x24, 0xaa, 0x55, 0x96, 0x0c,
	0x64, 0x0f, 0x36, 0x04, 0x7a, 0x1c, 0xa5, 0x52, 0x6d, 0xb2, 0x74, 0x22, 0x6d, 0xa8, 0x09, 0xfc,
	0x36, 0xc1, 0xd0, 0x43, 0x25, 0xdd, 0x64, 0x8b, 0x99, 0xfe, 0xa9, 0xc0, 0x26, 0x9b, 0x0d, 0x42,
	0x92, 0x33, 0xd8, 0x1a, 0xa2, 0xcc, 0x7e, 0x4f, 0xc9, 0x34, 0x4e, 0x1e, 0x76, 0x73, 0x5e, 0x74,
	0x53, 0xf0, 0x87, 0x3c, 0xd0, 0x31, 0x58, 0x91, 0x49, 0x2e, 0xa0, 0x25, 0x62, 0x0c, 0xfd, 0x9c,
	0x58, 0x55, 0x89, 0x3d, 0xd2, 0x89, 0x0d, 0x8a, 0x50, 0xc7, 0x60, 0xcb, 0x6c, 0xd2, 0x83, 0xe6,
	0x10, 0xe5, 0xdc, 0x55, 0x61, 0xad, 0x29, 0xb5, 0xa3, 0x92, 0xa3, 0x2d, 0x85, 0x20, 0x1c, 0x83,
	0x15, 0xe8, 0xe4, 0x14, 0x1a, 0x1c, 0xb9, 0x1b, 0xfa, 0xd1, 0x38, 0xf8, 0x81, 0xd6, 0xba, 0x52,
	0x7b, 0xa0, 0x53, 0x63, 0x19, 0xcc, 0x31, 0x58, 0x9e, 0x45, 0x9e, 0xc1, 0xfa, 0xd7, 0xd1, 0x44,
	0x5c, 0x5a, 0x1b, 0x8a, 0x7e, 0xa0, 0xa3, 0xbf, 0x9f, 0x01, 0x1c, 0x83, 0x25, 0xc8, 0x37, 0x9b,
	0x69, 0x70, 0xf4, 0x29, 0xec, 0xea, 0x9c, 0xd4, 0x27, 0x4b, 0x7f, 0x9b, 0xb0, 0xa7, 0xf7, 0x8a,
	0xbc, 0x00, 0xf0, 0x32, 0x93, 0x4d, 0x75, 0x92, 0xfd, 0x6e, 0xba, 0xa9, 0xdd, 0xfe, 0x6c, 0x2d,
	0x07, 0xc1, 0x30, 0x74, 0xe5, 0x84, 0x23, 0xcb, 0x41, 0xc9, 0x6b, 0xa8, 0x8f, 0xe7, 0x0b, 0x95,
	0x26, 0xdd, 0x29, 0x3c, 0x81, 0x66, 0xf1, 0x58, 0x46, 0x21, 0x2f, 0xa1, 0x16, 0xa7, 0x7e, 0xa6,
	0xd9, 0x1e, 0x16, 0xe8, 0x4b, 0x19, 0xb0, 0x05, 0x9a, 0x1e, 0x42, 0xbb, 0x3c, 0x2a, 0xda, 0x03,
	0x72, 0xdd, 0xfa, 0x5b, 0x3f, 0x26, 0xdd, 0x86, 0x66, 0x3e, 0x0a, 0xfa, 0xab, 0x0a, 0x35, 0x86,
	0x22, 0x8e, 0x42, 0x81, 0x33, 0x0f, 0xf0, 0xbb, 0x87, 0xb1, 0x0c, 0xa2, 0x30, 0x15, 0xbd, 0xbf,
	0x94, 0x62, 0x82, 0x7c, 0x37, 0x47, 0x39, 0x06, 0xcb, 0x28, 0xe4, 0xa3, 0xbe, 0x31, 0x54, 0xab,
	0xb1, 0xa2, 0x32, 0xfd, 0xb2, 0xca, 0x3c, 0xd6, 0xaa, 0xfd, 0x43, 0x67, 0xce, 0xb5, 0x9d, 0x39,
	0x2e, 0x3b, 0xdc, 0xca, 0xd2, 0xbc, 0xd5, 0x95, 0xa6, 0xa3, 0x95, 0xbb, 0xa1, 0x35, 0x27, 0xc5,
	0xd6, 0xb4, 0xb5, 0xfc, 0xb2, 0xda, 0x3c, 0x81, 0x3b, 0xd7, 0x22, 0x99, 0x75, 0x06, 0x39, 0x8f,
	0x78, 0xfa, 0x1f, 0x9b, 0x0c, 0xf4, 0xa7, 0x09, 0x77, 0xb5, 0xd6, 0xff, 0xb7, 0xca, 0xd0, 0x03,
	0xd8, 0x2f, 0x89, 0x8f, 0x7e, 0x82, 0x7b, 0x37, 0x44, 0x41, 0x5e, 0x41, 0x3d, 0x5e, 0xe4, 0x68,
	0x76, 0xaa, 0x2b, 0xdb, 0x96, 0xc1, 0xe9, 0x39, 0xec, 0x68, 0x62, 0xb9, 0x7d, 0xa3, 0x5a, 0xb0,
	0x55, 0x88, 0xe9, 0xcb, 0x86, 0x7a, 0xf9, 0x3d, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x32, 0x1f,
	0xa1, 0xfa, 0x58, 0x07, 0x00, 0x00,
}
