// Copyright 2020 Nym Technologies SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// AddCocoNodePresence provides a mock function with given fields: c
func (_m *Controller) AddCocoNodePresence(c *gin.Context) {
	_m.Called(c)
}

// AddMixNodePresence provides a mock function with given fields: c
func (_m *Controller) AddMixNodePresence(c *gin.Context) {
	_m.Called(c)
}

// RegisterRoutes provides a mock function with given fields: router
func (_m *Controller) RegisterRoutes(router *gin.Engine) {
	_m.Called(router)
}

// Topology provides a mock function with given fields: c
func (_m *Controller) Topology(c *gin.Context) {
	_m.Called(c)
}
