// Copyright 2020 Nym Technologies SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/nymtech/nym/validator/nym/directory/models"
	mock "github.com/stretchr/testify/mock"
)

// GatewayHostSanitizer is an autogenerated mock type for the GatewayHostSanitizer type
type GatewayHostSanitizer struct {
	mock.Mock
}

// Sanitize provides a mock function with given fields: _a0
func (_m *GatewayHostSanitizer) Sanitize(_a0 models.GatewayHostInfo) models.GatewayHostInfo {
	ret := _m.Called(_a0)

	var r0 models.GatewayHostInfo
	if rf, ok := ret.Get(0).(func(models.GatewayHostInfo) models.GatewayHostInfo); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.GatewayHostInfo)
	}

	return r0
}
