// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Sanitizer is an autogenerated mock type for the Sanitizer type
type Sanitizer struct {
	mock.Mock
}

// Sanitize provides a mock function with given fields: input
func (_m *Sanitizer) Sanitize(input interface{}) {
	_m.Called(input)
}
